
export const environment = {
  production: false,
  DomainURL: "https://cms.giatmancua.vn/",  
  DomainWebsiteURL: "http://giatmancua.vn",
  APIOnlineURL: "https://cms.giatmancua.vn/",
  APIURL: "https://api.giatmancua.vn/",
  LoginURL: "https://login.giatmancua.vn/",
  Images: "images",  
  Download: "Download", 
  CADangKyExcelFileName: "CADangKy.xlsx",  
  CustomerExcelFileName: "Customer.xlsx",  
  InvoiceExcelFileName: "Invoice.xlsx",  
  ProductExcelFileName: "Product.xlsx",  
  LogoFile: "logo.png",  
  ImageFile: "default-image.png",
  LoadingFile: "loading.gif",
  InitializationString: "",  
  InitializationNumber: 0,    
  CAID: 2197,  
  BHXHID: 2182,  
  HoaDonDienTuID: 2193,  
  VNPTID: 1,  
  DoanhNghiepID: 1,  
  InitializationDateTime: new Date(),    
  DialogConfigWidth: "80%",
  WorkListDetailURL: "/WorkList/Detail",
  DoanhNghiepDetailURL: "/Membership/DoanhNghiep/Detail",
  NhanVienDetailURL: "/Membership/NhanVien/Detail",
  AM_PhieuYeuCauDetailURL: "/AMPhieuYeuCau/Detail",
  AM_PhieuYeuCauInfoURL: "/AMPhieuYeuCau/Info",
  AM_PhieuYeuCauHoanThanhURL: "/AMPhieuYeuCau/HoanThanh",
  MainID: "main",
  MembershipID: "MembershipID",
  FullName: "FullName",
  Phone: "Phone",
  Image: "Image",
  LoginSubURL: "/Login",
  DefaultSubURL: "Dashboard/TongQuan",
  ProvinceTitle: "Tỉnh Bà Rịa - Vũng Tàu",  
  PageTitle: "Trần gia",  
  DeleteConfirm: "Bạn muốn xóa dữ liệu này?",
  DeleteSuccess: "Xóa thành công.",
  DeleteNotSuccess: "Xóa không thành công.",  
  SaveSuccess: "Thay đổi thành công.",
  SaveNotSuccess: "Thay đổi không thành công.",    
  UploadSuccess: "Upload thành công.",
  UploadNotSuccess: "Upload không thành công.",   
  LoginNotSuccess: "Đăng nhập không thành công.",
};


